### ISSUE TITLE
transform_predx function

### ISSUE THREAD

**Issue by elray1** [cdcepi/predx#3]
You'd supply a predx object or list of predx objects and the name of the predx class you want to convert it to and it would return either the new predx_class if possible or NA if not (by element if a list).

Here's a shot at documentation/arguments:

```
#' Convert predx objects from one class to another.
#' 
#' @parameter x a predx object or list of predx objects
#' @parameter target_class character specifying predx class to convert to, e.g. "BinLwr"
#' @parameter cat optional: if target_class is "BinCat", character vector of categorical bin names.
#' @parameter lwr optional: if target_class is "BinLwr", numeric vector of lower bounds for bins
#' @parameter n optional: if target_class is "Sample", integer number of samples to use.  We may not need this?
```

Without getting complicated, it seems like a lot of the pairs of input and output classes have to return NAs.  I'm going with that in the below for now, but maybe another option would be to let the user specify a named vector giving input-output class mappings, or a function that calculates the appropriate output (and we provide default behaviors for that function in the cases below where we think we have a reasonable default option).

Suppose the class of `x` is `Binary`:
- If `target_class` is `BinCat`, return `NA`
- If `target_class` is `BinLwr`, return `NA`
- If `target_class` is `Point`, return `x@p`
- If `target_class` is `Sample`, return a sample of zeros and ones with size n and proportion of observations equal to 1 as close as possible to x@p given the specified sample size

Suppose the class of `x` is `BinCat`:
- If `target_class` is `Binary`, return `NA`
- If `target_class` is `BinLwr`, return `NA`
- If `target_class` is `Point`, return `NA`
- If `target_class` is `Sample`, return `NA`

Suppose the class of `x` is `BinLwr`:
- If `target_class` is `Binary`, return `NA`
- If `target_class` is `BinCat`, return `NA`
- If `target_class` is `Point`, return something like the midpoint of the bin that contains the median of the distribution
- If `target_class` is `Sample`, return a sample of (bin mid-points?  Unif(lwr[i], lwr[i+1])?) with size n and proportion of samples in each bin as close as possible to x@p given the specified sample size

Suppose the class of `x` is `Point`:
- If `target_class` is `Binary`, return `NA`
- If `target_class` is `BinCat`, return `NA`
- If `target_class` is `BinLwr`, return `NA`
- If `target_class` is `Point`, return `NA`

Suppose the class of `x` is `Sample`:
- If `target_class` is `Binary`, return `NA`
- If `target_class` is `BinCat`, return `NA`
- If `target_class` is `BinLwr`, get the proportion of samples in each bin
- If `target_class` is `Point`, return the median (or mean?  or user-specified?) of the samples.  Currently this would work because Sample and Point both represent numeric forecasts

**Comment by majohansson** [comment]
Implemented as transform_predx a couple months ago. Functionality for only some classes at this point.
